'use client';

import Link from 'next/link';
import { useState } from 'react';
import { useEffect } from 'react';
import { getCurrentUser, getMyPrinters, getOpenRfqs, type RfqRecord } from '../../../lib/api-client';
import { Icon } from './icons';
import { OwnerSidebar } from './sidebar';

export function OwnerDashboard() {
  const [available, setAvailable] = useState(true);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [liveRfqs, setLiveRfqs] = useState<RfqRecord[]>([]);
  const [printerCount, setPrinterCount] = useState(0);
  const [ownerName, setOwnerName] = useState('Your account');
  useEffect(() => {
    void getOpenRfqs().then(({ rfqs: nextRfqs }) => setLiveRfqs(nextRfqs)).catch(() => undefined);
    void getMyPrinters().then(({ printers }) => setPrinterCount(printers.length)).catch(() => undefined);
    void getCurrentUser().then(({ user }) => setOwnerName(user.name || user.email)).catch(() => undefined);
  }, []);
  const visibleRfqs = liveRfqs.slice(0, 4).map((rfq, index) => ({ initials: 'RF', name: 'Buyer request', meta: `${rfq.material ?? 'Flexible material'} · India`, title: rfq.title, detail: `${rfq.quantity ?? 1} parts · ${rfq.deadline ? `Due ${new Date(rfq.deadline).toLocaleDateString('en-IN', { day: '2-digit', month: 'short' })}` : 'Date flexible'}`, amount: 'Review request', color: index % 2 === 0 ? 'orange' : 'blue' }));

  return (
    <div className="od-app">
      <OwnerSidebar open={sidebarOpen} onClose={() => setSidebarOpen(false)} ownerName={ownerName} rfqCount={liveRfqs.length} />
      <main className="od-main">
        <header className="od-header">
          <button className="od-menu-button" onClick={() => setSidebarOpen(true)} aria-label="Open navigation"><Icon name="menu" size={21} /></button>
          <div className="od-breadcrumb"><span>Workspace</span><Icon name="chevron" size={13} /><strong>Overview</strong></div>
          <div className="od-header-actions"><button className="od-header-icon" aria-label="Search"><Icon name="search" size={18} /></button><button className="od-header-icon od-bell" aria-label="Notifications"><Icon name="bell" size={18} /><i /></button><Link className="od-header-avatar" href="#profile">{ownerName.slice(0, 2).toUpperCase()}</Link></div>
        </header>

        <div className="od-content">
          <section className="od-welcome-row">
            <div><p className="od-kicker">Your owner workspace <span className="od-kicker-rule" /> India</p><h1>Good morning, {ownerName}<span>.</span></h1><p className="od-subtitle">Your {printerCount || 'available'} machines are ready. Here’s what’s moving today.</p></div>
            <div className="od-welcome-actions"><Link className="od-text-link" href="/for-printer-owners">Owner guide <Icon name="external" size={14} /></Link><Link className="od-primary-button" href="/vendor"><span>Manage public page</span><Icon name="arrow" size={16} /></Link></div>
          </section>

          <section className="od-availability" aria-label="Printer availability">
            <div className="od-availability-copy"><span className="od-pulse"><span /></span><div><strong>Your workshop is visible</strong><p>New customers can request quotes from you right now.</p></div></div>
            <button className={`od-toggle ${available ? 'od-toggle-on' : ''}`} role="switch" aria-checked={available} onClick={() => setAvailable(!available)}><span className="od-toggle-knob" /><span>{available ? 'Available' : 'Paused'}</span></button>
          </section>

          <div className="od-dashboard-grid">
            <section className="od-panel od-rfq-panel" id="rfq-inbox">
              <div className="od-panel-heading"><div><p className="od-kicker">Needs your eye</p><h2>Incoming RFQs {liveRfqs.length > 0 && <span className="od-count">{liveRfqs.length}</span>}</h2></div><Link className="od-panel-link" href="/dashboard/owner/rfqs">See all <Icon name="arrow" size={15} /></Link></div>
              <div className="od-rfq-list">{visibleRfqs.length > 0 ? visibleRfqs.map((rfq) => <article className="od-rfq-row" key={rfq.title}><span className={`od-avatar od-avatar-${rfq.color}`}>{rfq.initials}</span><div className="od-rfq-main"><div className="od-rfq-customer"><strong>{rfq.name}</strong><span>{rfq.meta}</span></div><h3>{rfq.title}</h3><p><Icon name="clock" size={13} /> {rfq.detail}</p></div><div className="od-rfq-price"><strong>{rfq.amount}</strong><Link href="/dashboard/owner/rfqs">Review <Icon name="arrow" size={14} /></Link></div></article>) : <p className="od-empty-state">No buyer requests yet. New RFQs will appear here when customers submit them.</p>}</div>
            </section>

            <section className="od-panel od-quote-panel">
              <div className="od-panel-heading"><div><p className="od-kicker">Next step</p><h2>Ready to quote?</h2></div><span className="od-spark"><Icon name="bolt" size={16} /></span></div>
              <p className="od-quote-intro">When a buyer request arrives, open your RFQ inbox to review the design brief and send a real price and lead time.</p>
              <Link className="od-dark-button" style={{ color: '#fff', minHeight: 48 }} href="/dashboard/owner/rfqs">Open RFQ inbox <Icon name="arrow" size={15} /></Link>
            </section>
          </div>

          <div className="od-lower-grid">
            <section className="od-panel od-checklist-panel"><div className="od-panel-heading"><div><p className="od-kicker">Keep growing</p><h2>Set up your shop</h2></div></div><p className="od-checklist-copy">Complete your profile to appear higher in customer searches.</p><div className="od-checklist"><div className={printerCount > 0 ? 'od-check-done' : 'od-check-current'}><span>{printerCount > 0 ? <Icon name="check" size={13} /> : '1'}</span><div><strong>Add your first printer</strong><small>{printerCount > 0 ? `${printerCount} active printer${printerCount === 1 ? '' : 's'} listed` : 'No printers listed yet'}</small></div><Link href="/dashboard/owner/printers" aria-label="Manage printers"><Icon name="arrow" size={14} /></Link></div><div className="od-check-next"><span>2</span><div><strong>Set your service area</strong><small>Add the cities you can serve</small></div></div><div className="od-check-next"><span>3</span><div><strong>Upload a work sample</strong><small>Show customers what you make</small></div></div></div><Link className="od-checklist-link" href="/vendor">Manage workshop profile <Icon name="arrow" size={14} /></Link></section>
          </div>

          <footer className="od-footer"><span>3oD by Zester Product Studio <span className="od-footer-dot">•</span> Built for makers in India</span><span><Link href="/for-printer-owners">How 3oD works</Link><Link href="/login">Sign out</Link></span></footer>
        </div>
      </main>
      <style jsx global>{`
        .od-app { --od-ink:#1e201d; --od-muted:#70736c; --od-line:#dedfd8; --od-paper:#f7f8f3; --od-white:#fffefa; --od-orange:#f4633f; --od-orange-soft:#fff0e9; --od-green:#0f8a67; --od-green-soft:#e6f4eb; --od-blue:#5677d8; --od-violet:#9672ca; min-height:100vh; display:flex; background:var(--od-paper); color:var(--od-ink); font-family:'Plus Jakarta Sans',system-ui,sans-serif; }
        .od-app * { box-sizing:border-box; } .od-app a { color:inherit; text-decoration:none; } .od-app button { font:inherit; }
        .od-sidebar { width:248px; flex:0 0 248px; background:var(--od-ink); color:#f4f4ed; padding:27px 18px 20px; display:flex; flex-direction:column; min-height:100vh; position:sticky; top:0; height:100vh; z-index:20; }
        .od-brand-row { display:flex; align-items:center; justify-content:space-between; padding:0 11px; margin-bottom:36px; } .od-brand { display:flex; flex-direction:column; gap:4px; font-size:28px; line-height:1; font-weight:700; letter-spacing:-.08em; } .od-brand span { color:var(--od-orange); } .od-brand:after { content:'by Zester Product Studio'; color:#8f938a; font:500 8px 'DM Mono',monospace; letter-spacing:.02em; text-transform:uppercase; } .od-close-button { display:none!important; }
        .od-workspace-chip { display:flex; align-items:center; gap:10px; padding:10px 9px; border:1px solid #3b3e39; background:#292c28; margin:0 5px 30px; border-radius:8px; } .od-workspace-chip strong,.od-workspace-chip small { display:block; } .od-workspace-chip strong { font-size:12px; font-weight:600; } .od-workspace-chip small { color:#aeb1aa; font-size:10px; margin-top:2px; } .od-workspace-chip svg { margin-left:auto; color:#9b9e97; }
        .od-nav-label,.od-kicker,.od-stat-label { font-size:10px; line-height:1; letter-spacing:.13em; text-transform:uppercase; font-weight:600; } .od-nav-label { color:#7f847b; margin:0 12px 10px; } .od-nav { display:grid; gap:4px; } .od-nav-link { display:flex; gap:12px; align-items:center; padding:11px 12px; color:#aeb1aa; border-radius:6px; font-size:13px; transition:background .2s,color .2s; } .od-nav-link:hover { background:#292c28; color:#fff; } .od-nav-link b { margin-left:auto; font-size:10px; font-weight:600; color:#ffb49e; background:#4a2d26; padding:3px 6px; border-radius:10px; } .od-nav-active { background:#343832; color:#fff; } .od-nav-active svg { color:var(--od-orange); } .od-sidebar-bottom { margin-top:auto; } .od-sidebar-bottom .od-nav-link { margin-bottom:3px; } .od-sidebar-footer { margin:22px 6px 0; padding-top:16px; border-top:1px solid #3b3e39; color:#9b9e97; font-size:10px; display:flex; align-items:center; gap:6px; } .od-status-dot,.od-pulse { display:inline-flex; align-items:center; justify-content:center; width:7px; height:7px; border-radius:50%; background:#62c89e; } .od-live-pill { color:#62c89e; font-size:8px; letter-spacing:.1em; margin-left:auto; }
        .od-main { min-width:0; flex:1; } .od-header { height:76px; padding:0 44px; display:flex; align-items:center; border-bottom:1px solid var(--od-line); background:rgba(247,248,243,.92); } .od-breadcrumb { display:flex; gap:11px; align-items:center; color:#a0a39a; font-size:12px; } .od-breadcrumb svg { transform:rotate(0deg); } .od-breadcrumb strong { color:var(--od-ink); font-weight:600; } .od-header-actions { margin-left:auto; display:flex; align-items:center; gap:18px; } .od-header-icon,.od-menu-button,.od-more-button,.od-modal-close { border:0; background:transparent; color:var(--od-ink); padding:4px; cursor:pointer; position:relative; } .od-bell i { position:absolute; width:5px; height:5px; background:var(--od-orange); border-radius:50%; top:1px; right:1px; border:1px solid var(--od-paper); } .od-header-avatar,.od-avatar { display:inline-flex; align-items:center; justify-content:center; border-radius:50%; font-weight:700; } .od-header-avatar { background:var(--od-orange); color:#fff; width:32px; height:32px; font-size:10px; } .od-menu-button { display:none; }
        .od-content { max-width:1380px; margin:0 auto; padding:42px 44px 30px; } .od-welcome-row { display:flex; justify-content:space-between; align-items:flex-end; gap:30px; margin-bottom:34px; } .od-kicker { color:#969a91; margin:0 0 13px; } .od-kicker-rule { display:inline-block; width:22px; height:1px; margin:0 8px 3px; background:#c1c4ba; } h1,h2,h3,p { margin:0; } .od-welcome-row h1 { font-size:clamp(32px,4vw,48px); line-height:1; letter-spacing:-.07em; font-weight:600; margin-bottom:12px; } .od-welcome-row h1 span { color:var(--od-orange); } .od-subtitle { color:var(--od-muted); font-size:14px; } .od-welcome-actions { display:flex; align-items:center; gap:22px; padding-bottom:3px; } .od-text-link,.od-panel-link,.od-checklist-link { color:#676b63; font-size:12px; display:inline-flex; gap:7px; align-items:center; } .od-text-link:hover,.od-panel-link:hover,.od-checklist-link:hover { color:var(--od-orange); } .od-primary-button,.od-dark-button { display:inline-flex; align-items:center; justify-content:center; gap:18px; padding:13px 16px; border:0; cursor:pointer; font-size:11px; font-weight:600; letter-spacing:.01em; transition:transform .2s,box-shadow .2s; } .od-primary-button { background:var(--od-orange); color:#fff!important; border-radius:5px; box-shadow:0 5px 16px rgba(244,99,63,.16); } .od-primary-button:hover,.od-dark-button:hover { transform:translateY(-2px); box-shadow:0 7px 16px rgba(31,34,29,.13); } .od-dark-button { background:var(--od-ink); color:#fff; width:100%; border-radius:5px; }
        .od-availability { display:flex; align-items:center; justify-content:space-between; background:#e6f4ea; border:1px solid #c8e5d4; border-radius:8px; padding:13px 16px; margin-bottom:34px; } .od-availability-copy { display:flex; align-items:center; gap:12px; } .od-pulse { width:22px; height:22px; background:#bfe8d2; } .od-pulse span { width:7px; height:7px; background:var(--od-green); border-radius:50%; } .od-availability strong { font-size:12px; display:block; } .od-availability p { color:#59816d; font-size:11px; margin-top:3px; } .od-toggle { display:flex; align-items:center; gap:9px; color:#45735e; border:0; background:transparent; cursor:pointer; font-size:11px; font-weight:600; } .od-toggle-knob { display:block; width:34px; height:20px; border-radius:20px; background:#b4c3b9; padding:3px; position:relative; transition:background .2s; } .od-toggle-knob:after { content:''; width:14px; height:14px; display:block; border-radius:50%; background:#fff; transition:transform .2s; box-shadow:0 1px 2px rgba(0,0,0,.13); } .od-toggle-on .od-toggle-knob { background:var(--od-green); } .od-toggle-on .od-toggle-knob:after { transform:translateX(14px); }
        .od-section { margin-bottom:37px; } .od-section-heading,.od-panel-heading { display:flex; align-items:flex-end; justify-content:space-between; gap:20px; } .od-section-heading { margin-bottom:15px; } .od-section h2,.od-panel h2 { font-size:19px; line-height:1; letter-spacing:-.045em; font-weight:600; } .od-period-button { border:1px solid var(--od-line); background:#fff; color:#646860; border-radius:4px; padding:8px 10px; font-size:10px; display:flex; gap:12px; align-items:center; cursor:pointer; } .od-stats-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:12px; } .od-stat { min-height:125px; border:1px solid var(--od-line); border-radius:8px; padding:15px 16px; position:relative; overflow:hidden; } .od-stat-top { display:flex; justify-content:space-between; align-items:center; } .od-stat-label { color:#777a72; font-size:9px; letter-spacing:.08em; } .od-stat-icon { display:flex; align-items:center; justify-content:center; width:28px; height:28px; border-radius:6px; background:rgba(255,255,255,.5); color:#73776e; } .od-stat strong { display:block; font-size:27px; line-height:1; letter-spacing:-.065em; margin:20px 0 8px; font-weight:600; } .od-stat-change { color:#777a72; font-size:10px; } .od-stat-orange { background:var(--od-orange); border-color:var(--od-orange); color:#fff; } .od-stat-orange .od-stat-label,.od-stat-orange .od-stat-change { color:#ffe9e2; } .od-stat-orange .od-stat-icon { color:#c3482d; } .od-stat-green { background:var(--od-green-soft); border-color:#c8e5d4; } .od-stat-green .od-stat-change { color:var(--od-green); } .od-stat-ink { background:var(--od-ink); border-color:var(--od-ink); color:#fff; } .od-stat-ink .od-stat-label,.od-stat-ink .od-stat-change { color:#bcc0b8; } .od-stat-ink .od-stat-icon { color:#fff; background:#373b35; }
        .od-dashboard-grid,.od-lower-grid { display:grid; grid-template-columns:minmax(0,1.4fr) minmax(310px,.8fr); gap:16px; margin-bottom:16px; } .od-panel { background:var(--od-white); border:1px solid var(--od-line); border-radius:8px; padding:23px; min-width:0; } .od-panel-heading { align-items:flex-start; margin-bottom:20px; } .od-panel .od-kicker { margin-bottom:10px; } .od-panel h2 { display:flex; align-items:center; gap:9px; } .od-count { font-size:10px; font-weight:600; color:var(--od-orange); background:var(--od-orange-soft); padding:4px 7px; border-radius:12px; letter-spacing:0; } .od-panel-link { color:#8a8d85; font-size:10px; white-space:nowrap; margin-top:21px; } .od-rfq-list { border-top:1px solid var(--od-line); } .od-rfq-row { display:grid; grid-template-columns:34px minmax(0,1fr) auto; align-items:start; gap:12px; padding:17px 0; border-bottom:1px solid var(--od-line); } .od-avatar { width:34px; height:34px; font-size:10px; flex:0 0 auto; color:#fff; background:var(--od-orange); } .od-avatar-small { width:27px; height:27px; font-size:8px; background:#66715d; } .od-avatar-blue { background:var(--od-blue); } .od-avatar-violet { background:var(--od-violet); } .od-rfq-customer { display:flex; align-items:baseline; gap:8px; } .od-rfq-customer strong,.od-rfq-main h3 { font-size:12px; font-weight:600; } .od-rfq-customer span,.od-rfq-main p { color:#999c94; font-size:10px; } .od-rfq-main h3 { margin:5px 0 6px; } .od-rfq-main p { display:flex; align-items:center; gap:5px; } .od-rfq-main p svg { color:#a2a69d; } .od-rfq-price { text-align:right; } .od-rfq-price strong { font-size:11px; display:block; margin:2px 0 9px; } .od-rfq-price button { border:0; color:var(--od-orange); background:transparent; padding:0; font-size:10px; font-weight:600; display:inline-flex; align-items:center; gap:4px; cursor:pointer; } .od-more-rfq { display:flex; align-items:center; gap:11px; padding:14px 0 1px; color:#666a62; } .od-more-rfq > svg { margin-left:auto; color:#a5a89f; } .od-more-icon { display:flex; width:30px; height:30px; justify-content:center; align-items:center; background:#f2f2ec; border-radius:5px; color:#8a8d84; } .od-more-rfq strong { font-size:11px; display:block; } .od-more-rfq p { font-size:10px; color:#9a9d95; margin-top:3px; }
        .od-quote-panel { background:#f2f0e9; border-color:#e2dfd4; } .od-spark { width:28px; height:28px; display:flex; align-items:center; justify-content:center; border-radius:50%; color:var(--od-orange); background:#fff; } .od-quote-intro,.od-checklist-copy { color:#767a70; font-size:11px; line-height:1.5; max-width:330px; margin-bottom:17px; } .od-quote-preview { background:#fff; border:1px solid #e4e1d8; padding:15px; margin:2px 0 16px; border-radius:5px; box-shadow:0 3px 12px rgba(44,45,39,.04); } .od-preview-top { display:flex; justify-content:space-between; color:#b0b0a8; font-size:8px; letter-spacing:.12em; padding-bottom:13px; border-bottom:1px solid #edece7; } .od-preview-title { display:flex; align-items:center; gap:10px; padding:14px 0 13px; } .od-preview-part { display:block; width:29px; height:29px; background:linear-gradient(140deg,#ef6d4b 40%,#f8b19f 41% 58%,#ed5e3b 59%); border-radius:5px 9px 5px 9px; transform:rotate(-9deg); } .od-preview-title strong,.od-preview-title small { display:block; } .od-preview-title strong { font-size:10px; } .od-preview-title small { color:#9b9e95; font-size:9px; margin-top:4px; } .od-preview-line,.od-preview-total { display:flex; justify-content:space-between; font-size:9px; padding:7px 0; color:#858980; } .od-preview-line strong { color:var(--od-ink); font-weight:600; } .od-preview-total { border-top:1px solid #edece7; margin-top:2px; padding-top:12px; color:var(--od-ink); font-weight:600; } .od-preview-total strong { font-size:15px; letter-spacing:-.04em; } .od-quote-note { text-align:center; color:#999b94; font-size:9px; margin-top:11px; } .od-quote-note strong { color:#6d7269; }
        .od-lower-grid { grid-template-columns:minmax(0,1.4fr) minmax(300px,.8fr); } .od-jobs-list { border-top:1px solid var(--od-line); } .od-job-row { display:grid; grid-template-columns:78px minmax(130px,1fr) minmax(160px,1.2fr) 58px 18px; gap:15px; align-items:center; padding:16px 0; border-bottom:1px solid var(--od-line); } .od-job-id { font:600 9px 'DM Mono',monospace; color:#858980; } .od-job-status { display:block; width:max-content; font:500 8px 'Space Grotesk',sans-serif; padding:4px 6px; margin-top:7px; border-radius:12px; } .od-job-status-orange { color:#b34c32; background:var(--od-orange-soft); } .od-job-status-green { color:#2d8065; background:var(--od-green-soft); } .od-job-info strong,.od-job-info span { display:block; } .od-job-info strong { font-size:11px; } .od-job-info span { font-size:9px; color:#9a9e94; margin-top:5px; } .od-progress-label { display:flex; justify-content:space-between; font-size:9px; color:#888c83; margin-bottom:6px; } .od-progress-label strong { color:#5f645b; } .od-progress { height:5px; border-radius:5px; background:#ededE7; overflow:hidden; } .od-progress span { display:block; height:100%; border-radius:5px; background:var(--od-orange); } .od-job-status-green + * .od-progress span,.od-job-row:nth-child(2) .od-progress span { background:var(--od-green); } .od-job-amount { font-size:11px; text-align:right; } .od-more-button { color:#a4a79f; }
        .od-progress-badge { color:#328167; background:var(--od-green-soft); border-radius:12px; padding:5px 8px; font-size:10px; font-weight:600; } .od-checklist-copy { max-width:280px; } .od-checklist { border-top:1px solid var(--od-line); margin-top:4px; } .od-check-done,.od-check-current,.od-check-next { display:flex; align-items:center; gap:10px; padding:11px 0; border-bottom:1px solid var(--od-line); } .od-check-done > span,.od-check-current > span,.od-check-next > span { width:19px; height:19px; flex:0 0 19px; display:flex; align-items:center; justify-content:center; border-radius:50%; font-size:9px; } .od-check-done > span { color:#fff; background:var(--od-green); } .od-check-current > span { color:var(--od-orange); border:1px solid var(--od-orange); } .od-check-next > span { color:#adb0a8; border:1px solid #d1d3ca; } .od-checklist strong,.od-checklist small { display:block; } .od-checklist strong { font-size:10px; font-weight:600; } .od-checklist small { color:#9b9e96; font-size:9px; margin-top:3px; } .od-check-current button { margin-left:auto; border:0; background:var(--od-orange-soft); color:var(--od-orange); border-radius:4px; width:26px; height:26px; display:flex; justify-content:center; align-items:center; cursor:pointer; } .od-checklist-link { margin-top:17px; color:var(--od-orange); font-weight:600; font-size:10px; }
        .od-footer { display:flex; justify-content:space-between; gap:20px; padding:24px 0 0; color:#a0a39a; font-size:9px; } .od-footer span span { color:#c4c6bd; padding:0 5px; } .od-footer > span:last-child { display:flex; gap:20px; } .od-footer a:hover { color:var(--od-orange); }
        .od-modal-backdrop { position:fixed; inset:0; z-index:40; display:flex; align-items:center; justify-content:center; padding:20px; background:rgba(26,28,25,.44); backdrop-filter:blur(4px); } .od-modal { width:min(420px,100%); background:var(--od-white); border-radius:10px; padding:30px; position:relative; box-shadow:0 18px 60px rgba(0,0,0,.2); } .od-modal-close { position:absolute; top:17px; right:17px; color:#858980; } .od-modal h2 { font-size:27px; line-height:1.02; letter-spacing:-.06em; margin-bottom:12px; } .od-modal p:not(.od-kicker) { color:var(--od-muted); font-size:13px; line-height:1.55; margin-bottom:22px; } .od-modal-cta { width:100%; }
        @media (max-width:1080px) { .od-sidebar { width:220px; flex-basis:220px; } .od-content,.od-header { padding-left:28px; padding-right:28px; } .od-job-row { grid-template-columns:72px minmax(120px,1fr) minmax(120px,1fr) 50px 18px; gap:10px; } }
        @media (max-width:820px) { .od-sidebar { position:fixed; left:-260px; top:0; transition:left .25s; box-shadow:8px 0 28px rgba(0,0,0,.14); } .od-sidebar-open { left:0; } .od-close-button { display:flex!important; color:#aaa; } .od-sidebar-scrim { position:fixed; inset:0; z-index:19; border:0; background:rgba(22,24,21,.35); } .od-menu-button { display:block; margin-right:14px; } .od-header { padding:0 20px; } .od-content { padding:34px 20px 24px; } .od-welcome-row { display:block; } .od-welcome-actions { margin-top:23px; justify-content:space-between; } .od-stats-grid { grid-template-columns:repeat(2,1fr); } .od-dashboard-grid,.od-lower-grid { grid-template-columns:1fr; } .od-rfq-panel,.od-quote-panel,.od-jobs-panel,.od-checklist-panel { min-height:0; } }
        @media (max-width:520px) { .od-header { height:66px; } .od-breadcrumb { font-size:11px; } .od-header-actions { gap:12px; } .od-header-icon:first-child { display:none; } .od-content { padding-top:27px; } .od-welcome-row h1 { font-size:36px; } .od-subtitle { font-size:13px; line-height:1.4; } .od-welcome-actions { gap:14px; } .od-text-link { font-size:10px; } .od-primary-button { padding:12px 12px; gap:10px; font-size:10px; } .od-availability { align-items:flex-start; gap:12px; } .od-availability-copy { align-items:flex-start; } .od-availability p { max-width:180px; line-height:1.35; } .od-toggle { flex-direction:column; gap:3px; font-size:9px; } .od-section-heading,.od-panel-heading { align-items:flex-start; } .od-stats-grid { gap:8px; } .od-stat { min-height:114px; padding:13px 12px; } .od-stat strong { font-size:23px; margin-top:17px; } .od-stat-change { font-size:9px; } .od-rfq-row { grid-template-columns:30px minmax(0,1fr); gap:10px; } .od-rfq-price { grid-column:2; text-align:left; display:flex; align-items:center; gap:12px; } .od-rfq-price strong { margin:0; } .od-rfq-price button { margin-left:auto; } .od-panel { padding:18px 16px; } .od-job-row { grid-template-columns:1fr auto; gap:10px; } .od-job-info { grid-column:1; } .od-progress-wrap { grid-column:1 / -1; } .od-job-amount { grid-column:2; grid-row:2; } .od-more-button { grid-column:2; grid-row:1; } .od-footer { display:block; line-height:1.8; } .od-footer > span:last-child { margin-top:8px; } }
        @media (prefers-reduced-motion:reduce) { .od-primary-button,.od-dark-button { transition:none; } }
      `}</style>
    </div>
  );
}
